# Setup and Introduction to Arrays

NumPy is arguably the most fundamental Python library in the realm of data science and machine learning. It's rare to find a data science project in Python that does not use NumPy in some way (directly or indirectly).

NumPy stands for **Numerical Python** and is used to work with numerical data, supporting operations in linear algebra, matrix manipulation, and much more.

## Installation

To install NumPy, we can use the following terminal command

```
pip install numpy
```

## Importing

To use NumPy in a Python program, we need to first import it, generally at the top of the file.

Usually, NumPy is imported under the alias `np`. The typical import statement is as follows:

In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

## NumPy arrays

NumPy is so popular because of the functionalities that its **arrays** provide. Arrays are similar to Python's traditional `list`s, just specialized for data science and numerical computation. Unlike `list`s, NumPy arrays are also homogeneous (can only store one type of data in one array).

Because of its optimization for large data and numerical computation, NumPy arrays are faster than lists and also require less space to store the same data. It also provides a great number of capabilities that data scientists need.

### Creating arrays

NumPy has many many functions that can be used to create arrays for different purposes. The most basic way of making an array is the `np.array()` function, into which we can pass some `list`, `tuple`, or some other array-like object.

In [3]:
arr1 = np.array([[1, 2, 3],
                 [2, 3, 4],
                 [3, 4, 5]])
print(arr1)
print(type(arr1))
print()

arr2 = np.array(((1.3, 2.2, 3.1),
                 (2.9, 3.5, 4.1),
                 (3.2, 4.4, 5.6)))
print(arr2)
print()

print(np.array([1, "Hi"]))  # Notice how 1 is converted to a str
print(np.array([1, 3.21]))  # Notice how 1 is converted to a float

[[1 2 3]
 [2 3 4]
 [3 4 5]]
<class 'numpy.ndarray'>

[[1.3 2.2 3.1]
 [2.9 3.5 4.1]
 [3.2 4.4 5.6]]

['1' 'Hi']
[1.   3.21]


### Commonly used attributes

Here are some of the most used and important attributes of an NumPy array.

* `arr.shape`: dimensions of the array ("depth")
* `arr.ndim`: number of dimensions (technically called axes) of the array
* `arr.size`: total number of elements in the array
* `arr.dtype`: data type the array stores

In [4]:
arr = np.array([
    [1, -2, 3, -4],
    [-1, 2, -3, 4]
])

print(f"{arr.shape = }")
print(f"{arr.ndim = }")
print(f"{arr.size = }")
print(f"{arr.dtype = }")

arr.shape = (2, 4)
arr.ndim = 2
arr.size = 8
arr.dtype = dtype('int32')


### Arithmetic operations

Among the many differences between `list`s and NumPy arrays is that arithmetic operations are done element-wise for arrays.

In [5]:
l = [1, 2, 3]
print(l)
# print(l + 2)  # TypeError: can only concatenate list (not "int") to list
print([num + 2 for num in l])

[1, 2, 3]
[3, 4, 5]


In [6]:
arr = np.array([1, 2, 3])
print(arr)
print(arr + 2)
print(arr - 10)
print(arr * 3)
print(arr / 2)

[1 2 3]
[3 4 5]
[-9 -8 -7]
[3 6 9]
[0.5 1.  1.5]


In [7]:
a = np.array([1, 2, 3])
b = np.array([-1, -2, -3])

print(a + b)
print(a * b)

[0 0 0]
[-1 -4 -9]


## Summary

Today, we learned about:

* Installing and importing `numpy`
* Creating NumPy arrays
* Important attributes of `numpy` arrays
* Arithmetic operations with `numpy` arrays