# Indexing and Slicing

Just like with `list`s, NumPy arrays support **indexing** (accessing an element using an index) and **slicing** (accessing elements using start and end indices).

In [1]:
import numpy as np

## Indexing/slicing 1D arrays

For one-dimensional arrays, the syntax of indexing and slicing are the same as with `list`s and `tuple`s.

```python
arr[index]            # Indexing
arr[start:stop:step]  # Slicing
```

In [2]:
l = list(range(10))
a = np.array(l)

print(l)
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(l[3])
print(a[3])

3
3


In [4]:
print(l[1:4])
print(a[1:4])

[1, 2, 3]
[1 2 3]


In [5]:
print(l[1:6:2])
print(a[1:6:2])

[1, 3, 5]
[1 3 5]


In [6]:
print(l[::-1])
print(a[::-1])

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[9 8 7 6 5 4 3 2 1 0]


## Indexing/slicing ND arrays

When indexing and slicing arrays with multiple dimensions, we pass in either an index or a slice for each dimension of the array in square brackets, separated by commas.

```python
arr[
    start_outer:stop_outer:step_outer,
    start_inner:stop_inner:step_inner
]  # For 2D arrays
```

In [7]:
arr = np.array([
    [1, 2, 3, 4],
    [10, 20, 30, 40],
    [100, 200, 300, 400],
    [1000, 2000, 3000, 4000],
    [10000, 20000, 30000, 40000]
])
print(arr)

[[    1     2     3     4]
 [   10    20    30    40]
 [  100   200   300   400]
 [ 1000  2000  3000  4000]
 [10000 20000 30000 40000]]


In [8]:
print(arr[1, 2])

30


In [9]:
print(arr[1:3, 2])

[ 30 300]


In [10]:
print(arr[:4:2, 2:4])

[[  3   4]
 [300 400]]


Sometimes, you will see `...` in the square brackets. `...`, called `Ellipsis`, is used to fill up the number of `:` needed for all the dimensions. For example, the lines below are equivalent.

In [11]:
arr = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 23], [24, 25, 26]]
])

print(arr[2], end="\n\n")
print(arr[2, :, :], end="\n\n")
print(arr[2, ...], end="\n\n")

[[19 20 21]
 [22 23 23]
 [24 25 26]]

[[19 20 21]
 [22 23 23]
 [24 25 26]]

[[19 20 21]
 [22 23 23]
 [24 25 26]]



In [12]:
print(arr[..., 1])

[[ 2  5  8]
 [11 14 17]
 [20 23 25]]


## Modifying arrays using indexing and slicing

In addition to accessing values of an array using indexing and slicing, these operations also allow us to modify an array.

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr)

a = arr.copy()
a[1:6:2] = 0
print(a)

a = arr.copy()
a[1:6:2] *= -1
print(a)

a = arr.copy()
a[1:6:2] = [100, 300, 500]
print(a)

# a[1:6:2] = [1, 2, 3, 4]
# ValueError:
    # could not broadcast input array from shape (4,) into shape (3,)

[1 2 3 4 5 6 7]
[1 0 3 0 5 0 7]
[ 1 -2  3 -4  5 -6  7]
[  1 100   3 300   5 500   7]


## Summary

In this lesson, you learned about

* Indexing and slicing one-dimensional arrays
* Indexing and slicing multidimensional arrays
* Modifying arrays using indexing and slicing