# Reshaping Arrays

Reshaping is a very common operation with NumPy arrays. Many data science and machine learning methods only accept data of certain shapes, which may not be the original shapes of our data. Therefore, we often need to reshape our arrays into the desired shape.

In [1]:
import numpy as np

## Shape of an array

The shape of an array is determined by the number of elements it has in each dimension.

In [2]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.shape)

(2, 3)


## Flattening arrays

To flatten an array (putting all the elements into 1 dimension), we can use the `ravel()` method.

In [3]:
print(arr, end="\n\n")
print(arr.ravel(), end="\n\n")
print(arr)  # arr.ravel() returns a new array, original doesn't change

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]


## Reshaping arrays

We can reshape arrays using the `reshape()` and `resize()` methods.

`arr.reshape(shape)` returns a new array with the data of `arr` in the specified `shape`.

`arr.resize(shape)` modifies the original array and changes its shape to the specified `shape`.

In [4]:
print(arr, end="\n\n")
print(arr.reshape((3, 2)), end="\n\n")
print(arr)

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]


In [5]:
print(arr, end="\n\n")
arr.resize((6, 1))
print(arr)

[[1 2 3]
 [4 5 6]]

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


It is sometimes convenient to use `-1` as a dimension when reshaping. Let's say we have a dataset with many values, stored in the shape `(1, n)`. Some data science and machine learning functions want data with shape `(n, 1)`. We could use `arr.shape` to find out the exact value of `n`, or we can just use `-1` for that dimension, so `numpy` would calculate the value for us during reshaping.

In [6]:
arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
print(arr)
print(arr.shape)
print()

reshaped_arr = arr.reshape((-1, 1))
print(reshaped_arr)
print(reshaped_arr.shape)

[[1 2 3 4 5 6 7 8 9]]
(1, 9)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(9, 1)


## Expanding dimensions

The `np.expand_dims()` function is used to expand the shape of an array.

```python
np.expand_dims(arr, axis)
```

returns `arr` with its number of dimensions increased, done by adding an additional dimension at the position specified by `axis`.

In [7]:
arr = np.array(range(10))
print(arr)
print(arr.shape)
print()

new_arr = np.expand_dims(arr, axis=0)
print(new_arr)
print(new_arr.shape)
print()

new_arr = np.expand_dims(arr, axis=1)
print(new_arr)
print(new_arr.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)

[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


NumPy has the `atleast_1d()`, `atleast_2d()`, and `atleast_3d()` functions, which are used to convert arrays into arrays with at least `1`, `2`, or `3` dimensions.

In [8]:
arr = np.array(range(16))
print(arr.shape)

print(np.atleast_1d(arr).shape)
print(np.atleast_2d(arr).shape)
print(np.atleast_3d(arr).shape)

(16,)
(16,)
(1, 16)
(1, 16, 1)


## Removing dimensions

The inverse of `np.expand_dims()` is `np.squeeze()`, which removes dimensions of length 1 from an array.

In [9]:
arr = np.array(range(16)).reshape((1, 2, -1, 2, 1))
print(arr.shape)

print(np.squeeze(arr).shape)
print(np.squeeze(arr, axis=0).shape)
print(np.squeeze(arr, axis=4).shape)
try:
    print(np.squeeze(arr, axis=2).shape)
except ValueError as e:
    print(e)

(1, 2, 4, 2, 1)
(2, 4, 2)
(2, 4, 2, 1)
(1, 2, 4, 2)
cannot select an axis to squeeze out which has size not equal to one


## Summary

In this lesson, you have learned several ways to manipulate the shape of arrays, including

* Flattening using `ravel()`
* Reshaping using
    * `reshape()`
    * `resize()`
* Expanding dimensions using
    * `expand_dims()`
    * `atleast_1d()`
    * `atleast_2d()`
    * `atleast_3d()`
* Removing dimensions using `squeeze()`